### ISSUE TITLE
v4.0.0a beta - Reverting post header change rarely doesn't work, seemingly focused on select users?

### ISSUE THREAD

**Issue by Camwoodstock** [enchanted-sword/dashboard-unfucker#101]
**Describe the bug**
For some reason, on one of my mutuals specifically, the post header change that unhides what blog was being reblogged from fails to work. It doesn't happen on every post, but it happens on a good few of them.

**To Reproduce**
I'm gonna be real here--I don't have any wise ideas beyond supplying the blog of the friend in question.
https://www.tumblr.com/uboatan/727024313203556352

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/107432951/fbf50be9-05dd-4713-bf2a-b6c4b11dad77)

**Version (please complete the following information):**
 - Browser: Firefox v117.0
 - Version: 4.0.0a Beta

**Additional context**
I get the feeling this is _not_, in fact, a problem exclusive to just my mutual, and there's some underlying factor that they just keep hitting for one reason or another? Whatever that may be, your guess is as good as mine.

**Comment by enchanted-sword** [comment]
The post is reblogged from a deactivated blog, which doesn't link to anything, and the script checks for `find(post.querySelectorAll(`:scope ${keyToCss("label")}`), `a[href="/${rebloggedFromName}"]`)`, hence why it fails to find the name. However, this is easily fixed by instead just selecting the last label in the `nodeList` since the name that's missing is always the last one attached to the post. This even saves checking the NPF data!

**Comment by enchanted-sword** [comment]
Also, previously, since it processed each array of modifications at a time, if the first post in the array threw an error it wouldn't process the rest of the array, hence why the bug was showing up for every post.
