### ISSUE TITLE
looks like tumblr reverted the header design; now unfucker breaks them (on new layout)

### ISSUE THREAD

**Issue by frenchifries** [enchanted-sword/dashboard-unfucker#103]
it appears on my end, when i fully disable tampermonkey, that post headers look normal again, with icons displaying where they used to and everything. however, because the dashboard unfucker was trying to fix this, it actually messes them up again when using the new layout (looks fine on the reverted/old layout). alas the struggle of trying to fix something that tumblr is actively fucking around with lol.

without dashboard unfucker:
<img width="648" alt="Screen Shot 2023-08-31 at 5 38 55 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/142453425/539618e9-e8be-4c87-a864-c98c75f9a5c6">

with dashboard unfucker (no icon fix):
<img width="565" alt="Screen Shot 2023-08-31 at 5 38 45 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/142453425/5a1c3b58-4060-421f-aa0a-85d57b4fa381">

with dashboard unfucker + icon fix:
<img width="648" alt="Screen Shot 2023-08-31 at 5 39 35 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/142453425/27ef7480-8b8b-4571-a013-658565fc6835">

**Comment by enchanted-sword** [comment]
Not even sure what causes this, I couldn't even get it to happen consistently, (and the fact that in each case it still displays the 3px border radius is a whole different story) but this, combined with a whole slew of other issues, has finally convinced me to just depricate the "revert vertical navigation layout" toggle since it's not worth the headache of trying to support the new layout in the script, especially when the whole purpose of the script is to revert the vertical navigation layout anyways.
