### ISSUE TITLE
Multi Columns of posts?

### ISSUE THREAD

**Issue by anoraktrend** [enchanted-sword/dashboard-unfucker#123]
**Describe the feature**
multiple columns of posts on the dashboard, like on the search page.
**Additional context**
make it an option slider like dash size and location.

**Comment by enchanted-sword** [comment]
While this is likely possible, I don't think I will add this. 

The reason why a masonry layout is useful for the search and tagged pages is because it gives a broad overview of a larger number of posts; which is useful when, of course, searching, or browsing tagged posts. For most people, however, a masonry layout is likely too "cluttered" for a dedicated dashboard layout due to the narrower posts, smaller avatars, and multiple streams of content. Of course, there are no doubt people other than yourself who would actively use such a feature, but given the fact that I haven't seen any other interest in such a feature, within this repository or on Tumblr in general, I won't be adding it at this time

**Comment by anoraktrend** [comment]
I am literally using a tv as a main screen, so just making the posts wider doesn't feel like an efficient way for using up all the space. Also, multiple feeds is something else entirely but it's something that might be useful for some people.

**Comment by enchanted-sword** [comment]
FWIW I was planning to implement this in Dashboard Plus before I realized that even with access to Tumblr's frontend source code something like this would be nigh impossible to implement without either rewriting the entire dashboard timeline page or finding a way to force hydrate the dashboard as masonry.
