### ISSUE TITLE
Search bar row function inaccessible when viewing blog pages, blog-specific button functionality partially covered up on blog pages

### ISSUE THREAD

**Issue by ColorMeBrackets** [enchanted-sword/dashboard-unfucker#130]
**Describe the bug**

When going to any blog's page, the search button and the other functions of the row it's on are inaccessible, and the functionality for the buttons above that row (Ask, Follow, TumblrMart, Message, and the Meatball menu button) are only accessible if clicked on small sections at the very top of each respective button.

It seems to be related to [this previous bug](https://github.com/enchanted-sword/dashboard-unfucker/issues/127) reported by kawa-z. While the visual blocking of the buttons as reported by kawa-z is gone, the functionality still seems busted as-if covered up, and higher buttons seem to have been "partially" covered up.

**To Reproduce**

1 Go to https://www.tumblr.com/dashboard
2. Click on the icon of any user on the left side of posts
3. Hover over the magnifying glass icon, "Posts" button, or blog-arrangement-style buttons and see that the mouse cursor does not change and that clicking on them does not do anything, and that only small parts of the Ask, Follow, TumblrMart, Message, and the Meatball menu buttons allow for functionality.
or
1. Go to https://www.tumblr.com/dashboard
2. Type in the blog's username in the place of "dashboard"
3. Hover over the magnifying glass icon, "Posts" button, or blog-arrangement-style buttons and see that the mouse cursor does not change and that clicking on them does not do anything, and that only small parts of the Ask, Follow, TumblrMart, Message, and the Meatball menu buttons allow for functionality.

**Version (please complete the following information):**
 - Browser and version:  Firefox 117.0.1 (64-bit)
 - Version: 4.4.3

**Additional context**
The Ask, Follow, TumblrMart, Message, and Meatball menu buttons are _not_ covered up when viewing a blog through the "https://www.tumblr.com/ [blog name] / [post id]" version of blog links, though that does not give access to the search bar or its associated row's contents.

**Comment by enchanted-sword** [comment]
Whoops, didn't catch this because I have it set to redirect to only the proper `https://blogname.tumblr.com` links instead. The buttons are definitely because of the offset: 
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/243b5195-13b0-42d3-93a9-2515ad2d3799)
At first I thought the broken scroll offsets didn't apply to these permalink pages, however they seem to be MORE broken if possible, and instead scroll...233px above the bottom of the page. What gives?
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/6487caf0-e627-4a55-a06b-a266ad9907ca)

**Comment by enchanted-sword** [comment]
Should be fixed in v4.4.4
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/ad7ea070-8610-4b5e-ba3a-17d1fc63e8e3)
