### ISSUE TITLE
J+K scrolling a little messed up when viewing someone's blog

### ISSUE THREAD

**Issue by ghostlygunk** [enchanted-sword/dashboard-unfucker#132]
scrolling through posts on the dashboard with the J and K hotkeys work fine, but when on someone's blog the scrolling is off-center and puts the 'next' post at the very bottom of the screen rather than centering it like it does on the dashboard, which is fine for smaller textposts but cuts off anything longer. 

example of a smaller post pushed to the bottom:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/129334938/4b727035-18ba-487b-9825-05e39c26a38b)

example of a longer post getting cut off:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/129334938/9f830610-0691-42d1-8208-0e2b3fda8a38)

idk, it's probably silly to report. using firefox ver. 117, unfucker version 4.4.4

**Comment by enchanted-sword** [comment]
This is currently intentional; the dashboard offset is a consistent 100px but permalink pages are a lot more messed up, and it doesn't seem consistent between blogs or devices. Additionally, offsetting the `main` div on permalink pages blocks the follow, search, etc. icons, which can be fixed with z-index, but the main problem still remains.

**Comment by ghostlygunk** [comment]
i see! thank you
