### ISSUE TITLE
Ability to toggle the dashboard unfucking

### ISSUE THREAD

**Issue by victorianchimneysweep** [enchanted-sword/dashboard-unfucker#134]
This is probably an issue only I have, but basically: I actually don't mind the twitterified dashboard, or at least I find it less annoying than the page flashing different layouts as it loads, but I also really like some of the other features this script has. Would it be possible to toggle between the old and new layout the way you can toggle the old and new activity and messaging windows?

**Comment by enchanted-sword** [comment]
I originally removed that feature specifically because not all of the features worked properly with the new dashboard. You can modify the script yourself by removing the line `{"name": "redpopDesktopVerticalNav", "value": false},`, but it isn't guaranteed to work perfectly.

It might in theory be possible to fix all the compatibility issues (except perhaps messaging), but the extra work required to maintain compatibility with both the old and new layouts just isn't worth it for me, especially since reverting to the old layout is the main purpose of the script.
