### ISSUE TITLE
An ption to get the big avatars back without changing the whole layout

### ISSUE THREAD

**Issue by moonflowcr** [enchanted-sword/dashboard-unfucker#143]
As someone who has gotten used to the new layout design but hates the last update regarding how the avatars show up (inside the post headers instead of outside the post, the way it was before and got reverted to after their little experiment a few months ago) because needs to have those there for visual reference, I would love to see an option to get those back without altering the new sidebars layout.

**Comment by moonflowcr** [comment]
Thank you so much for the fix! Is there a possibility you could add the hide/disable options in the dashboard unfucker to this or to an individual script in the future (general configuration options + everything under advanced configuration but the revert the layouts and messaging redesign)? I like some of the functionalities in it, but I'm not really interested in changing the layout again now I'm used to it for the sake of muscle memory.

(I wasn't sure if I should continue talking in this same issue or not, so let me know if you prefer me to start a new one and refer to this)

**Comment by enchanted-sword** [comment]
It depends. I initially stopped supporting the old layout for other feature changes because it broke messaging entirely regardless of if the messaging redesign was enabled or not. It's possible that could have been fixed on Tumblr's end by now, but who knows. I'd definitely have to retest all the features for compatibility with the new layout, which might take a bit, but its worth looking into.
