### ISSUE TITLE
Tumblr page seems to refresh after initial load as of 5.2.0

### ISSUE THREAD

**Issue by aetherspoon** [enchanted-sword/dashboard-unfucker#146]
**Describe the bug**
When loading a new Tumblr page, the page loads and then refreshes very shortly after its initial load, causing the "last read" position to change to the most recent post.

**To Reproduce**
1. Open a new tab.
2. Visit tumblr.com

**Version (please complete the following information):**
 - Browser: Firefox 118.0.1 (Linux x64) and 118.0.1 (Windows 10 x64)
 - Version: 5.2.0. It is possible that 5.x.x is the source of the bug (as I had not used any prior version in the 5.x.x series), but I did not notice it on the prior 4.x.x version I was using.

**Additional context**
This occurs on multiple of my computers, and only occurs when visiting tumblr.com from either a new tab or a tab not currently on tumblr. A simple page refresh does _not_ trigger the same issue.
I do have other browser extensions installed, but other than a standard uBlock Origin and Ghostery, I don't have any extensions that would affect Tumblr and TamperMonkey only has dashboard-unfucker loaded.

**Comment by enchanted-sword** [comment]
If your account was created after May 2023 then Tumblr tries to default to the "For You" feed instead of the regular feed. The extra load is the page navigating to "/following".

If your account is older than that, I'm not sure what would cause that, unless the script is failing to execute events after the document has loaded. If that's the case, there should be a related error message in the console.

**Comment by aetherspoon** [comment]
My account is definitely older than that. :)

I see four errors in the console when I load the page - three cross-origin requests, one chunkloaderror. These are the same regardless of whether this is on refresh or on initial load though, so I don't think they're related; I can send them over if it'll help troubleshooting though.

**Comment by enchanted-sword** [comment]
It seems the second reload is actually caused by the page reverting to the old layout, but I'm not sure why that refreshes the timeline. Oddly enough, although it moves the dividing section to the top of the timeline it doesn't update the position that the "Now, where were we..." button navigates you to. I'm not sure if there's a way to prevent this second reload from updating the divider position, but I'll see if there's any way to move it to where it should be, since I believe the last position in the timeline is either saved in storage or cookies or in the `___INITIAL_STATE___` variable.

**Comment by aetherspoon** [comment]
I am still seeing the same issue as of 5.3.0; I don't believe this is resolved.

**Comment by enchanted-sword** [comment]
Whoops, I fixed it with the show hidden posts feature active, but it wasn't applying when the setting was off. Should be good in v5.3.2.
