### ISSUE TITLE
Remove the carousel when Live is disabled through tumblr itself

### ISSUE THREAD

**Issue by anthroApologizing** [enchanted-sword/dashboard-unfucker#172]
**Describe the feature**
If you turn off Live through tumblr itself, it leaves behind this annoying section that appears both at the top of the dashboard or sometimes in between posts.  It'd be amazing if it could be removed, because it's beyond obnoxious with the cringy title text.

**Additional context**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/126769975/2ebdd734-a7be-4e21-9796-e9842cfb5e6e)

**Comment by enchanted-sword** [comment]
That isn't part of Live, it's the divider section that marks where you last left off when scrolling through the timeline. I haven't done anything to modify it since XKit Rewritten already has a feature that collapses it into a dividing line, and while that feature recently broke, I just [PRed a fix for it today](https://github.com/AprilSylph/XKit-Rewritten/pull/1340).

That being said, I may revisit it once I'm on break since it does fit the scope of this script, but it depends.
