### ISSUE TITLE
Trying to reblog a post results in a blank page

### ISSUE THREAD

**Issue by catte-go-nya** [enchanted-sword/dashboard-unfucker#180]
Whenever I try to reblog a post now, I can't. It just goes to a white page.

1. See a post
2. Click reblog button on the post
3. The screen becomes blank and white

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/98241923/8c9aa3a3-53e3-4b65-a391-dbec9b55a6c4)

- Firefox 120.0.1 (64-Bit, Linux)

This happened at the same time the header got really tall (see Wuzzle's post about it)

**Comment by enchanted-sword** [comment]
Are there any associated errors in the console?

**Comment by catte-go-nya** [comment]
there's this really big one that repeats the same url over and over, if that helps
![Screenshot from 2023-12-08 10-58-19](https://github.com/enchanted-sword/dashboard-unfucker/assets/98241
![Screenshot from 2023-12-08 10-58-23](https://github.com/enchanted-sword/dashboard-unfucker/assets/98241923/2e662904-bd9e-467a-a495-58d95137db2a)
923/703f22a1-a631-4567-b3a1-84daf62ad1e9)

**Comment by enchanted-sword** [comment]
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/2f217528-c840-4f4b-83ed-bf0b169a6082)
This one would be the culprit, can you expand it so I can see the traceback?

**Comment by enchanted-sword** [comment]
Weird, I messed around with sending a test error to find what should be line 1584 (the number in the console doesn't actually correspond to the number in my IDE) and the `$()` function isn't used there.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/0c556500-9ed4-48e3-9e4b-5d97d8c009a9)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/3457623f-1f50-4679-9d02-c47744b4bcce)

Additionally, I'm not sure what could throw `TypeError: $(...) is null`, since it differs from all the related errors thrown by that function.

**Comment by catte-go-nya** [comment]
After a fresh install, I noticed this also happens without the unfucker, and is an issue pertaining to something else.
Sorry.
