### ISSUE TITLE
Extension fails to work in Chrome regular browser, works in Incognito

### ISSUE THREAD

**Issue by whiteangel123** [enchanted-sword/dashboard-unfucker#186]
**Describe the bug**
The error happened after I received a notification that Tampermonkey got corrupted. After reinstalling Tampermonkey and the unfucker script, error still persist. The "Dashboard Unfucker" little menu on the top right doesn't even appear. I've tried hiding all the other extension in case it's a clash with the adblock/antivirus, but no luck.
Extension works in Firefox and Chrome Incognito, but not regular Chrome. 

**To Reproduce**
1. Open tumblr
2. See error

**Screenshots**
Regular browser:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/36785520/96ab37bf-cb87-4a30-8d2b-4a376b6ea0db)
Incognito:

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/36785520/165d7b3e-a894-4adc-af93-cf70e1106c1f)

**Version (please complete the following information):**
 - Browser and version: Chrome 120.0.6099.71
 - Version 5.5.2

**Additional context**
In Firefox it appears to clash with UBlock Origin, but turning off Ublock fixes the issue. In Chrome, nothing I do can make the Unfucker script function properly again. Ublock is active in Chrome Incognito, but doesn't affect Dashboard Unfucker there.

**Comment by whiteangel123** [comment]
Not sure if this helps, but when I tried to check for Errors in Dev Mode I saw this:

Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'advanced' in 1
    at <anonymous>:199:25
    at Array.forEach (<anonymous>)
    at unfuckDashboard (<anonymous>:198:49)
    at <anonymous>:1663:5
    at b (eval at buildCode (dashboard:606:31), <anonymous>:5:866)
    at He (eval at buildCode (dashboard:606:31), <anonymous>:5:48496)
    at S.fn.init.append (eval at buildCode (dashboard:606:31), <anonymous>:5:49847)
    at Object.eval (eval at buildCode (dashboard:606:31), <anonymous>:1714:27)
    at Object.eval (eval at buildCode (dashboard:606:31), <anonymous>:1716:3)
    at Object.eval (eval at buildCode (dashboard:606:31), <anonymous>:1717:3)
6Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by enchanted-sword** [comment]
It seems there's something very strange going on here.
The script loads preferences via this method:
```js
const currentPreferences = JSON.parse(window.localStorage.getItem('configPreferences'));
const currentKeys = Object.keys(currentPreferences);
for (const key in configPreferences) {
  if (currentKeys.includes(key)) {
    if (typeof configPreferences[key] === 'object') {
      Object.keys(configPreferences[key]).forEach(function (val) {
        if (!(val in currentPreferences[key])) {
          currentPreferences[key][val] = configPreferences[key][val];
        }
      });
    }
    configPreferences[key] = currentPreferences[key];
  }
}
updatePreferences();
```
The line throwing the error in your case would be ` if (!(val in currentPreferences[key])) {`, which is somehow trying to check for the key `advanced` in the number `1` instead of the proper object. I have no idea how this would even end up happening, but I'll see if I can add extra validation to the preference loading.

It's only working in Incognito because Incognito doesn't save storage between sessions and thus it will always use the default configs instead of trying to load whatever broken data is currently saved to your regular browser. You should be able to fix it manually by just opening the browser console with F12, going to the "Storage" tab, and deleting the `configPreferences` item under Local Storage, which will reset your preferences and fix the bad parsing.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/d3d814e3-96bc-4cfd-a36d-c3d718d16de1)


The CSP stuff isn't related to the script since it's clearly actually running it, or at least trying to.

**Comment by enchanted-sword** [comment]
Chrome should still have an equivalent to it.

**Comment by whiteangel123** [comment]
Thank you the error has been resolvved
