### ISSUE TITLE
Unfucker not opening and causing New Xkit to not work 

### ISSUE THREAD

**Issue by maswartz** [enchanted-sword/dashboard-unfucker#188]
For a few days now the Unfucker has had issues loading and now today it flat out will not load or even show up. Furthermore it is preventing New Xkit from working as well, I'll disable the unfucker and New Xkit will work fine but not the other way around.

**Comment by enchanted-sword** [comment]
Are there any related errors in the console?

**Comment by maswartz** [comment]
How do I find that?

**Comment by enchanted-sword** [comment]
F12
Not sure what browser you're using, but in Firefox at least you can filter it to show only errors (these ones are all unrelated to the script)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/42c37e92-c6e6-4851-979e-58e3a1f3408a)
> According to someone it's Tampermonkey's update that screwed everything up

Tampermonkey v5.0.0 (And Tampermonkey beta before it) work normally for me on all of my computers, so I would think it to be a conflict with another extension or some other external issue.
That being said, I am using Firefox 121 and most of the reported issues using Tampermonkey are on Firefox 120, so it could be an issue specific to that version of Firefox, although I did test on 120 once and found it to work normally, though I haven't tested it in conjunction with New XKit on 120.

New XKit has always been slightly finicky in combination with this script, although I've personally never found any issues with it when testing, so it's probably not an obvious issue that I could find by looking through the New XKit source code.

**Comment by maswartz** [comment]
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: nonce-source or hash-source specified dashboard
[XKit Bridge] Hello from Bridge 2.2.1 bridge.js:72:10
[XKit Bridge] Retrieving storage.. bridge.js:73:10
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). dashboard line 9 > injectedScript:3:865
[XKit Bridge] Storage loaded, calling XKit.. bye! bridge.js:108:12
Loading failed for the <script> with source “https://s0.wp.com/wp-content/js/bilmur.min.js?m=202350&f=3”.

**Comment by enchanted-sword** [comment]
Unfortunately, none of those logs have any relevant information.

**Comment by Rudicron** [comment]
I was having the same issue, and after raising the Log Level in TM, I saw that  immediately following the following log lines:
`env: run "dashboard unfucker" ASAP -> document-start [content.js:57:293](moz-extension://2d437272-ec1d-483d-a2b0-3dbe635724f9/content.js)`
`env: inject "dashboard unfucker" now [content.js:56:86](moz-extension://2d437272-ec1d-483d-a2b0-3dbe635724f9/content.js)`
was that Content-Security-Policy line (`Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). dashboard line 9 > injectedScript:3:865`)

This actually led me to a possible solution (at least, it worked for me); 

1. enter the Tampermonkey settings (click the Tampermonkey icon, click "Dashboard", then go to the Settings tab)
2. make sure that the Config Mode is set to Advanced (needed to see the option below)
3. scroll down to the Security section, and set the "Modify existing content security policy (CSP) headers" option to "Yes" (mine was on Auto, and that wasn't good enough)

It should look a little something like this:
![Tampermonkey settings for dashboard unfucker - Modify Existing CSP](https://github.com/enchanted-sword/dashboard-unfucker/assets/14276837/47008ab1-c5c2-4ba0-a399-959c403065da)

I'd already had that option set in the Chrome version, and that was showing no problems, displaying everything as it should be.
Once I set it in Firefox, (wasn't set because it was a fresh install) the script started properly unfucking.

**Comment by enchanted-sword** [comment]
The script theoretically shouldn't require modifying the CSP headers, but it's good to know that it does resolve the issue. I'll add that to the FAQ if it does work for other people as well.

**Comment by namara-ashina** [comment]
I'm having the same issue where Unfucker is no longer working on my dashboard. I tried the above fix but it didn't change anything

**Comment by namara-ashina** [comment]
i was using tampermonkey before but i tried installing the script in greasermonkey and violentmonkey and none are not working on dashboard

**Comment by AbelardTullus** [comment]
I'm encountering this issue as well, although Unfucker doesn't seem to conflict with Xkit at all, as disabling one or the other doesn't actually fix the issue, it's possible this is an issue on Tumblr's end, but I couldn't say for sure.

Here's the errors printed out from running just Unfucker.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/20971561/2000ac87-51e4-40c8-87a0-d49a59202bfd)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/20971561/d621a7f5-ba67-41e9-bb53-3e4db723e34a)

**Comment by citrusella** [comment]
> most of the reported issues using Tampermonkey are on Firefox 120, so it could be an issue specific to that version of Firefox

I had similar behavior occasionally (this and New XKit not loading, though reloads usually fixed it) two days ago on 115 (current ESR version) so at the very least it's not *specific* to 120 (even if a version later than 120 fixed it).

**Comment by namara-ashina** [comment]
dunno if this will help but, unfucker is still refusing to function on my tumblr dash EXCEPT FOR the members page of my side-blogs. i've tested it on multiple side-blogs and it's the only place it magically starts working again.

**Comment by AbelardTullus** [comment]
> dunno if this will help but, unfucker is still refusing to function on my tumblr dash EXCEPT FOR the members page of my side-blogs. i've tested it on multiple side-blogs and it's the only place it magically starts working again.

I've found this to be the case on the members page exclusively, the script doesn't seem to work on any other page.

**Comment by citrusella** [comment]
I'm not this extension's maintainer, but given the appearance I see on the members page of one of my sideblogs I'm pretty sure it's a page that doesn't need this script loaded to look like that anyway (it appears to be one of a handful of pages Tumblr itself didn't change to the new layout--and by that I mean it hasn't been updated for *years* and is still on the *old* legacy dash, because XKit extensions that were never updated to the 2020 React dashboard (AKA the one that broke most of XKit for a bit a few years back) will still load on it).

(There are a handful of pages that just always load in the non-react dash layout (which was never Twitter-ified)--you can usually tell because the active blog is listed in the sidebar instead of "check out these blogs" and radar (and the person-shaped dropdown, prior to the blog lists, will only have likes, following, settings, and help, no matter what the settings of any script you have that could hide those things on the current dash says). If you don't have anything that might be affecting your navbar width, you can also tell because the React pages' navbar spans the full width of the window whereas the legacy dash has it centered/limited to the width of the content (i.e. the Tumblr logo is above the side where the avatars are instead of in the left upper corner, the icons on the other side are similarly pulled inward).

You can even get to the dashboard in legacy mode temporarily by visiting bad post form URL, i.e. like this reblog URL ostensibly for a post on my blog except I just put random numbers at the end instead https://www.tumblr.com/reblog/citrusella-flugpucker/54789587945879897. It will kick you out to the legacy dash, instead of the current dash. Sharing because it feels useful in the context of allowing comparison between "current dash with this script" and "never-Twitterified legacy dash".)

**Comment by AbelardTullus** [comment]
Absolute hero, tysm 💖

**Comment by KairoseAerostar** [comment]
I'm also having this issue, as of last night, on both Firefox 120 and 121. It would occasionally work correctly on refresh prior to updating to 121, but I have not yet experienced that on 121.

Including this script, I currently have 5 things that would modify tumblr: New xkit, xkit Rewritten, uBlock Origin, an "Anti-Adblock Killer" Tampermonkey script, and this script. Disabling tampermonkey entirely allowed the two xkit extensions to function, as did disabling only this script. Disabling anti-adblock killer but leaving this script enabled did not help, so it is clear the issue is something related to this script. 

The following is the log outputs with and without this script enabled. Though there are still a few errors, this may help clarify which ones are caused by dashboard unfucker.
[unfucker console.txt](https://github.com/enchanted-sword/dashboard-unfucker/files/13827503/unfucker.console.txt)
[non-unfucker console.txt](https://github.com/enchanted-sword/dashboard-unfucker/files/13827507/non-unfucker.console.txt)

**Comment by enchanted-sword** [comment]
I can't see any differences in these logs that would indicate why New XKit would stop working specifically with the script enabled. New XKit is throwing errors in both cases, with the only difference being that it's CSP errors instead of TypeErrors when the script is running, and the script wouldn't be the cause of those CSP errors.

On an unrelated side note, that anti-adblock killer script doesn't actually appear to be injecting successfully, my best guess is that it runs too early and/or doesn't have a mutation listener/callback for when `document.head` is ready.

**Comment by citrusella** [comment]
I notice when the loading of this and/or XKit partially or completely fails, there are no console entries related to "sentry". (Some of the console entries for that in a successful load are clearly related to this script and appear to be setting flags--some appear to be from Tumblr instead.)

i.e. the following kinds of console entries don't happen on a failed load:

```
Object { acceptWebpUploads: true, activityHighlightUnread: true, activityRedesignM3: true, adFreeBrowsingGifts: true, adFreeCtaBanner: true, adFreeSubscriptionStat: true, adsRefreshEnabled: true, adultContentAppealTextbox: true, androidHttp2Support: true, anonymousExplorer: true, … } sentry-a4b6c873.js:18:18228
Array(17) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ] sentry-a4b6c873.js:18:18228
unfucking dashboard... sentry-a4b6c873.js:18:18228
dashboard fixed! sentry-a4b6c873.js:18:18228
```

The last three are clearly from this script it looks like, but the first one appears to be from Tumblr.

I don't know if that's at all helpful or related to the issue, but it's something I saw...

**Comment by enchanted-sword** [comment]
The first one is also from the script.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/907076f1-d134-41cd-b87e-d7bcb97346f1)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/fc250465-dad8-44e5-bdac-12ff645901af)

**Comment by citrusella** [comment]
Ah! I couldn't figure out if it was or not, so I decided since it didn't seem to match my settings it must not be. Oops!
