### ISSUE TITLE
Some elements seemingly get randomly replaced <> a symbol with 2 greater than/lesser <> symbols?

### ISSUE THREAD

**Issue by Camwoodstock** [enchanted-sword/dashboard-unfucker#192]
**Describe the bug**
For whatever reason, some elements either don't load or get replaced by a symbol with the two <> symbols.

**To Reproduce**
1. Go to basically any page.
2. Scroll down as much as necessary to load enough elements.
4. Almost inevitably, it appears.

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/107432951/aaa152e1-d50a-4425-8c7c-558b6b79fcda)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/107432951/8554b192-b3f5-4b9d-abbe-270cba80a263)

**Version (please complete the following information):**
 - Firefox 120.0.1 (64-bit)
 - Version 5.5.7

**Additional context**
The <> buttons are links if you hover over them, but they don't actually lead anywhere.

**Comment by enchanted-sword** [comment]
Judging by the placements of the carets it looks like they're connected to the dashboard tabs carousel and the "Biggest fans" carousel.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/e419065a-7717-4023-88f4-0ea2c440a6e0)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/29369cb8-ae5d-4108-bc08-e09e223c70af)
Both of those seem to work normally for me (although the blog cards don't normally overflow in the horizontal nav layout for me and I had to duplicate one of the nodes to make them show up).

I'm not sure how exactly they'd end up like that, especially since the carets are normally hidden and they collapse automatically if the rest of the carousel is hidden.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/a42f91e2-5bf7-4160-a979-a67faf8ab700)

**Comment by Camwoodstock** [comment]
Double-checking our uBlock Origin filters, the culprit seems to have been an item called "! www.tumblr.com##.jxu4l > div"--however, upon re-enabling it, a few in-line ads start appearing. And for whatever reason, our profile icon next to the "post" bar has disappeared.

...We have literally no idea what to make of this, though this admittedly is almost certainly out of the scope of the Dashboard Unfucker. ;P

**Comment by enchanted-sword** [comment]
That selector targets `scrollContainer > div` elements and the caret child elements of the container are `buttons` and not `divs`, so that does check out.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/5243b998-56f3-4691-851e-c0395303b87f)
I'm not sure if the bar icon thing is related, but I would check your other custom filters as well to make sure they aren't doing anything unintended.
