### ISSUE TITLE
follower and post count not visible in the dropdown menu

### ISSUE THREAD

**Issue by maltsea** [enchanted-sword/dashboard-unfucker#26]
i updated to the latest version of unfucker. yes i did ctrl+shift+r. i use version 6.1.3035.257 of vivaldi on windows 11, if that matters at all. i understand it's not a huge issue but i thought i'd report it anyway.
![16c79afe562ecc7e1cc9c98ec7f9ed72](https://github.com/enchanted-sword/dashboard-unfucker/assets/60683032/60f1363a-5242-4200-8c2f-001408b0e1fd)

**Comment by enchanted-sword** [comment]
This is part of an update on tumblr's end that completely removes the account stats menu from dashboard pages, and the only reason it's showing up at all is because I wrote a fix to re-add it this morning. However, I wasn't able to re-implement the post/follower/activity/drafts/queue counters because those require an API key.

![258582724-3a488184-e970-4c31-a1da-e1491025bf56](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/084941e3-259d-469c-8d3d-bd69935cc141)
(This is what it looks like without v2.0.5)
