### ISSUE TITLE
updates after 1.3 not working

### ISSUE THREAD

**Issue by netherprince** [enchanted-sword/dashboard-unfucker#30]
on firefox, any version of the script after 1.3 just does not work for me. they install, but nothing gets changed- dash remains on the sidebar, all the layout is the same. i've tried clearing the cache, turning off all my other extensions, and both, to no avail.

**Comment by enchanted-sword** [comment]
With the amount I've changed since 1.3 in terms of how the script executes, and the fact that it doesn't even partially execute and stop partway though, I think the problem here has to lie outside of the script itself. The first thing I would check is that both the script and Tampermonkey are currently enabled:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/5cb625d3-121e-46d5-bd84-700ba7e31873)
After that, the only thing I can think of is to make sure the extension has all the required permissions in the Add-ons Manager (about:addons).

**Comment by netherprince** [comment]
oh, i just realized the problem: i was using greasemonkey and not tampermonkey. switching fixed it. my bad!
