### ISSUE TITLE
Going to another page of the dashboard makes profile images not load, shows 'Follow' button

### ISSUE THREAD

**Issue by Avakining** [enchanted-sword/dashboard-unfucker#33]
See screenshot below. This is the second page of the dashboard (endless scrolling turned off). Every post is missing the profile picture and there is a 'Follow' button next to every username.

<img width="646" alt="Screenshot 2023-08-16 at 15 09 45" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/25210618/e4356d5f-d448-4ccb-9e89-b50bbfe50f51">

macOS 13.5
Firefox 116.0.3
Tampermonkey 4.19.0
Script version 3.2.3
XKit Rewritten 0.21.15

Note: only applies to version A

**Comment by enchanted-sword** [comment]
This bug is actually Tumblr's fault, I just did tests with multiple accounts with the script disabled and it still appeared as blank. I thought it was connected to the new `redpopVirtualScroller` experiment, but disabling it doesn't seem to fix it. Since it's a server-side issue, I expect it should be fixed soon, but if not I'll see about incorporating a fix for it. As a side note, if you just want to disable the "follow" buttons, there's an XKit Rewritten tweak for that.

**Comment by enchanted-sword** [comment]
Reopening until Tumblr fixes it this so people don't continually report it as a new bug.
