### ISSUE TITLE
Porn Ban Toggle (lazy patch enclosed as proof of concept)

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [enchanted-sword/dashboard-unfucker#48]
If you recurse through PeeprRoute.initialTimeline, the only thing that causes flagged posts not to show up when browsing someone's blog or looking directly at a URL is a "isNsfw: true" key being set on the specific post. Here's a barebones preview of what you'd have to do to change this — don't add this version, though. The proper way to do it would be to actually parse the initialTimeline object and check specifically on post objects instead of blindly checking every object down the tree for 'isNsfw'.

```js
const updateObject = (old) => {
    let copy = JSON.parse(JSON.stringify(old));
    //console.log(copy)
    for (let i in old) {
        if (typeof old[i] === "object") {
            copy[i] = updateObject(copy[i]);
        } else if (typeof old[i] === "array") {
            copy[i] = copy[i].map(x=>typeof x === "object"?updateObject(x):x)
        } else {
            if(i==='isNsfw') copy['isNsfw'] = false;
        }
    }
    return copy;
};

Object.defineProperty(window, "___INITIAL_STATE___", { // thanks twilight-sparkle-irl!
    set(x) {
        state = x;
    },
    get() {
        try {
            return {
                ...state,
                PeeprRoute: updateObject(state.PeeprRoute),
                obfuscatedFeatures: modifyObfuscatedFeatures(state.obfuscatedFeatures, featureSet)
            };
        } catch (e) {
            console.error("Failed to modify features", e);
        }
```

It's worth noting that this doesn't work that well and it's probably worth doing some other way, because if you change views it stops being "initial timeline," but I wanted to document that it's possible somewhere.

**Comment by enchanted-sword** [comment]
From what I can tell, `initialTimeline` seems to be the contents of the first `/v2/blog/{blogName}/posts` API call that the page makes while loading, as well as a link to the next API call to be made as the user is scrolling down through the first 17 posts. This does mean that it isn't really a useful object to modify, unless you wanted to add another object to the top of the timeline for some reason. But the concept of modifying `isNsfw` and other NPF object properties does still have some promise. The problem is figuring out how and when to modify it so that the effects actually show up in the DOM. I have a few random ideas:

1. I know XKit Rewritten uses a series of scripts that inject a `<script>` tag into the timeline object in order to fetch the post's NPF data without making an API call. I haven't looked at it super thoroughly, but if by some chance this data is not read-only, or at least the "meta" portion outside of the actual post content is, then that's a relatively streamlined way to make changes.
2. I doubt this is the case, but if the data fetched via the API while scrolling is stored in a different window property somewhere, then that data could be modified before the actual posts are rendered.
3. I'm not very knowledgeable on the network side of things, so perhaps this is a completely outlandish idea, but if you could intercept the results of the API calls, you could return a modified array of NPF objects.

**Comment by twilight-sparkle-irl** [comment]
>     3. I'm not very knowledgeable on the network side of things, so perhaps this is a completely outlandish idea, but if you could intercept the results of the API calls, you could return a modified array of NPF objects.

You could theoretically accomplish this by hooking `fetch` or `XMLHttpRequest`, whichever Tumblr uses. This would need to complement the initial timeline patch, as it doesn't refetch that data, but it holds promise.

**Comment by enchanted-sword** [comment]
Finally sat down and got around to fiddling with this. I was able to hook `fetch` to modify the `/timeline/` requests like such:
```js
  const fetchSelector = /\/api\/v2\/timeline/;
  const oldFetch = window.fetch;
  window.fetch = async (input, options) => {
    const response = await oldFetch(input, options);
    const content = await response.json();
    if (fetchSelector.test(input)) {
      const elements = content.response.timeline.elements;
      elements.forEach(post => post.isNsfw = false);
    }
    return new Response(JSON.stringify(content), {
        status: response.status,
        statusText: response.statusText,
        headers: response.headers
    });
  };
```
This seems to work as it should. I couldn't find any flagged posts to test it on, but by instead changing `post.isNsfw` to `true` it blocked every post after the initial set while also revealing an interesting fact; your own posts aren't part of the dashboard timeline, they're fetched separately. The next steps here are to also hook the fetch paths for `/blog/{blog}/posts/` api calls and also modify the initial timeline. This is found in the `PeeprRoute` object in permalink pages as you initially mentioned; I'm actually not sure where the initial timeline for the dashboard is stored.

**Comment by enchanted-sword** [comment]
Finally got around to finishing this, it's live on [this branch](https://github.com/enchanted-sword/dashboard-unfucker/tree/gen5). It doesn't seem to cause any performance issues, but I'll test it for a while before I merge it.
