### ISSUE TITLE
Dashboard Unfucker now just results in a blank page (Version B)

### ISSUE THREAD

**Issue by kiwi8fruit6** [enchanted-sword/dashboard-unfucker#74]
When I try to use Dashboard Unfucker with Tumblr, the new (fucked) website layout appears for a few seconds, then the whole tumblr page goes blank. No links, no buttons, no posts, no nothing. Just a blank screen. If I turn off the Dashboard Unfucker, the site returns to its new layout, but if I turn it back on again and refresh the page - same thing, blank screen. I have tried uninstalling and reinstalling the Dashboard Unfucker, also without success. 

**Screenshots**
![Screenshot 2023-08-24 at 9 58 53 AM](https://github.com/enchanted-sword/dashboard-unfucker/assets/143039939/b4140890-2831-4be0-bcc6-4c44a9a9d756) with Dashboard Unfucker on
![Screenshot 2023-08-24 at 9 59 06 AM](https://github.com/enchanted-sword/dashboard-unfucker/assets/143039939/b3306c93-de70-4ff4-aa1d-c3fa6729c605) with Dashboard Unfucker off

**Version**
 - Firefox version 116.0.3 (64-bit)
 - Dashboard Unfucker Version 4.1.4 (no flags)

**Additional context**
For me this issue only cropped up in the last few minutes. Is anyone else experiencing this bug, or could it be that Tumblr is somehow trying to block the Dashboard Unfucker?

**Comment by kiwi8fruit6** [comment]
Update: trying Version A instead of Version B has restored Tumblr functionality. 
![Screenshot 2023-08-24 at 10 16 14 AM](https://github.com/enchanted-sword/dashboard-unfucker/assets/143039939/67c66a60-9c38-4079-85ff-a1c39bd44ae4)

**Comment by enchanted-sword** [comment]
Same issue here as #66 and #70; it seems that there's some loading check done that resets the layout between when this script runs and when the page finishes loading, the blank appearance is only because the script stylesheet hides the default parent elements of the navbar and main content. As insane as it sounds, I wouldn't be surprised if this was actually an attempt to block the script because of how specific and unnecessary it is otherwise.

**Comment by mjharwood** [comment]
I have seen the same issue. WIth infinite scroll off, some pages would be black, others would be fine.
