### ISSUE TITLE
"re-add icons to reblogs" option disappeared

### ISSUE THREAD

**Issue by barlowgirl13** [enchanted-sword/dashboard-unfucker#82]
I went to a new page and icons on reblogs disappeared. Went down to check and it's just gone?

**Screenshots**
![Screenshot 2023-08-24 181118](https://github.com/enchanted-sword/dashboard-unfucker/assets/65017840/baa475bd-5640-45fe-8f49-44cbbbd6b872)

**Version (please complete the following information):**
 - Chrome version 116.0.5845.111
 - Version 3.6.5a]

**Comment by enchanted-sword** [comment]
You have "revert vertical nav layout" disabled, which automatically disables the "revert post header changes" toggle because the new layout is not backwards-compatible with the old header style and causes bugs.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/951efee1-4c08-4f66-a6ea-e298fa6c3b2f)
I may port version B's header fix to version A in the future as a compatibility feature for the new layout, but that's not my current priority.

**Comment by rarsneezes** [comment]
There was definitely an option to have icons with the new layout, though? It worked fine yesterday - yes it overlapped the sidebar, but that wasn't bothering me or anyone I've talked to. If this is the code not being compatible and it broke on tumblr's end, not yours, then I understand. But if re-adding icons was removed because of the left sidebar overlap, that doesn't make any sense to me.... Just wondering what happened to what [this post](https://rarmaster.tumblr.com/post/726409620956069888) promised haha.

**Comment by enchanted-sword** [comment]
As you can see in the picture, it doesn't overlap any more, it just sticks it on top. if you really want to, you can force toggle it by running `localStorage.setItem("configPreferences", '[{"type":"checkbox","value":""},{"type":"checkbox","value":""},{"type":"checkbox","value":""},{"type":"checkbox","value":""},{"type":"checkbox","value":""},{"type":"checkbox","value":""},{"type":"checkbox","value":""},{"type":"checkbox","value":""},{"type":"checkbox","value":""},{"type":"checkbox","value":"checked"},{"type":"checkbox","value":""},{"type":"checkbox","value":"checked"},{"type":"checkbox","value":""},{"type":"checkbox","value":"checked"},{"type":"checkbox","value":""},{"type":"checkbox","value":""},{"type":"checkbox","value":""}]')` in the browser console. I disabled it because a lot of people DID dislike the overlap or report it as a bug, but now it doesn't even display beside the post.

The main purpose of the script is, well, reverting the vertical navigation layout, and it does just that. Re-adding icons is a part of that feature— the method version A uses does not natively allow re-adding icons to the new layout, and version B doesn't have have a toggle for the new layout because that was its sole initial purpose. I am already using a `mutationObserver` in version A to fix empty data in the headers, so again, I may add a compatible icon fix to the new layout, but compatibility with the layout the script's sole purpose is to revert is not an immediate priority
